"""
SE5 — Physical Security Audit Kit
Toolkit for authorized physical-security assessments.
"""

import base64
import random


class AssetInventory:
    """Inventory builder for physical assets and access points."""

    def __init__(self, name="Site"):
        self.name = name
        self.assets = []
        self.access_points = []

    def add_asset(self, tag, asset_type, location, owner, classification="internal"):
        self.assets.append({
            "tag": tag, "type": asset_type, "location": location,
            "owner": owner, "classification": classification,
        })
        return self

    def add_access_point(self, label, kind, layering=1, lock_type="none"):
        self.access_points.append({
            "label": label, "kind": kind, "layering": layering,
            "lock_type": lock_type, "clearance": self._clearance(layering),
        })
        return self

    @staticmethod
    def _clearance(layering):
        if layering >= 3:
            return "high"
        if layering == 2:
            return "medium"
        return "low"

    def inventory_report(self):
        lines = [f"ASSET & ACCESS-POINT INVENTORY — {self.name}", ""]
        lines.append(f"Assets: {len(self.assets)}")
        for a in self.assets:
            lines.append(f"  [{a['tag']}] {a['type']} @ {a['location']} owner={a['owner']} ({a['classification']})")
        lines.append("")
        lines.append(f"Access Points: {len(self.access_points)}")
        for ap in self.access_points:
            lines.append(f"  [{ap['label']}] {ap['kind']} lock={ap['lock_type']} clearance={ap['clearance']}")
        return "\n".join(lines)


class LockoutQualification:
    """Strong lock practice / lock-pick-qualification tracking."""

    MODELS = ["Standard Pin Tumbler", "High-Security Pin", "Disc Detainer", "Wafer"]
    STATUS = ["untrained", "in-progress", "qualified"]

    def __init__(self):
        self.records = {}

    def register(self, technician, models=()):
        self.records.setdefault(technician, {})
        if isinstance(models, str):
            models = [models]
        for m in models or self.MODELS:
            self.records[technician].setdefault(m, "untrained")

    def mark(self, technician, model, status):
        self.records[technician][model] = status

    def report(self):
        lines = ["LOCK-PICK / BYPASS QUALIFICATION TRACKING", ""]
        for tech, models in self.records.items():
            q = sum(1 for s in models.values() if s == "qualified")
            tot = len(models)
            lines.append(f"  {tech}: {q}/{tot} models qualified")
            for model, status in models.items():
                lines.append(f"      {model:28s} → {status}")
        return "\n".join(lines)


class TailgatingSimulation:
    """Checklist generator for tailgating-simulation exercises."""

    BASELINE = [
        "Position a cleanly dressed observer at the target door (no badge, carrying items).",
        "Approach the door just behind a legitimate badge-holder.",
        "Wait for the holder to badge in, then step through as the door closes.",
        "Record whether anyone confronts the tailgater or challenges their entry.",
        "Note badge-latch behavior and physical door re-lock time.",
        "Attempt with 1 hand / 2 hands / both arms loaded to vary plausibility.",
        "Visit front desk request and camera-facing thresholds separately.",
        "Document incident reports generated by staff (or absence of them).",
        "Assess whether a mantraps, turnstiles, or security guards are present.",
        "Grade response: challenged / not noticed / verbally warned / detained.",
    ]

    def checklist(self, site="site", room=None, count=3):
        lines = [f"TAILGATING SIMULATION CHECKLIST — {site}", ""]
        lines.append(f"Personnel required: 2 (1 tailgater, 1 safety observer)")
        lines.append(f"Simulated door(s): {room or 'main entrance'}")
        lines.append("")
        for i in range(1, count + 1):
            lines.append(f"[Round {i}]")
        lines.append("")
        lines.append("Steps per round:")
        for idx, step in enumerate(self.BASELINE, 1):
            lines.append(f"  {idx:2d}. {step}")
        lines.append("")
        lines.append("Results log columns: time | door | challenged? | notes")
        return "\n".join(lines)


class BadgeRisk:
    """Badge-cloning risk analysis from supplied byte samples."""

    FORMATS = {
        "EDGE": {"mfg_bits": 8, "uid_bits": 32, "check_bits": 8},
        "HID PROX": {"mfg_bits": 8, "uid_bits": 26, "check_bits": 1},
        "Awid": {"mfg_bits": 8, "uid_bits": 36, "check_bits": 0},
    }

    def __init__(self, card_format="EDGE"):
        if card_format not in self.FORMATS:
            raise ValueError(f"Unsupported format {card_format!r}; use {list(self.FORMATS)}")
        self.format = card_format
        self.spec = self.FORMATS[card_format]

    def parse_raw(self, raw_bytes):
        """Parse a raw byte sample into manufacturer + UID components."""
        stream = base64.b64decode(raw_bytes) if isinstance(raw_bytes, str) else raw_bytes
        bits = "".join(f"{b:08b}" for b in stream)
        total = len(bits)
        spec = self.spec
        mfg = bits[:spec["mfg_bits"]]
        uid = bits[spec["mfg_bits"]: spec["mfg_bits"] + spec["uid_bits"]]
        check = bits[spec["mfg_bits"] + spec["uid_bits"]:]
        return {
            "format": self.format,
            "total_bits": total,
            "mfg_bits": spec["mfg_bits"],
            "uid_bits": spec["uid_bits"],
            "expected_bits": spec["mfg_bits"] + spec["uid_bits"] + spec["check_bits"],
            "manufacturer": mfg,
            "uid_hex": format(int(uid[:32] or "0", 2), "08x") if uid else "n/a",
            "uid_decimal": int(uid, 2),
        }

    def risk_assessment(self):
        """Estimate cloning risk on a low/medium/high scale."""
        uid_bits = self.spec["uid_bits"]
        if uid_bits <= 26:
            return "HIGH", "Short UID space: brute-force or replay feasible with commodity readers"
        if uid_bits <= 36:
            return "MEDIUM", "Moderate UID space; unauthenticated read/write doubles risk"
        return "LOW", "Large UID space; cloning still possible if unencrypted"


class AuditReport:
    """Generate a structured physical-security audit report."""

    def __init__(self, site="Example Site", date=None):
        self.site = site
        self.date = date or "audit date"
        self.sections = []

    def add_section(self, title, body):
        self.sections.append((title, body))

    def render(self):
        import datetime
        sep = "=" * 64
        lines = [sep,
                 f"  PHYSICAL SECURITY AUDIT REPORT",
                 f"  Site   : {self.site}",
                 f"  Date   : {self.date}",
                 "  Mode   : AUTHORIZED TESTING — RED TEAM",
                 sep, ""]
        for title, body in self.sections:
            lines.append(f"--- {title} ---")
            lines.append(body)
            lines.append("")
        lines.append(sep)
        lines.append("END OF AUDIT REPORT")
        return "\n".join(lines)


def sample_raw_card(format_name="EDGE"):
    spec = {"EDGE": (40,), "HID PROX": (35,), "Awid": (44,)}[format_name]
    bits = "".join(random.choice("01") for _ in range(spec[0] * 8))
    bits = bits[:40] if format_name == "EDGE" else bits[: spec[0] + 0]
    byte_len = (spec[0] + 7) // 8
    raw = random.randbytes(byte_len)
    return base64.b64encode(raw).decode()


def demo():
    random.seed(42)
    print("SE5 — PHYSICAL SECURITY AUDIT KIT (AUTHORIZED TESTING DEMO)")
    print()

    inv = (AssetInventory("ACME HQ")
           .add_asset("A-01", "Server Rack", "Data Center 1", "IT Ops", "confidential")
           .add_asset("A-02", "Workstation", "Engineering Floor", "Eng", "internal")
           .add_access_point("D-01", "Main Entrance", layering=1, lock_type="magnetic"))
    print(inv.inventory_report())
    print()

    lock = LockoutQualification()
    lock.register("R. Torres", ["Standard Pin Tumbler", "Disc Detainer"])
    lock.mark("R. Torres", "Standard Pin Tumbler", "qualified")
    lock.mark("R. Torres", "Disc Detainer", "in-progress")
    print(lock.report())
    print()

    print(TailgatingSimulation().checklist("ACME HQ", room="loading dock", count=2))
    print()

    print("BADGE-CLONING RISK ASSESSMENT (EDGE sample)")
    for fmt in ["EDGE", "HID PROX", "Awid"]:
        sample = sample_raw_card(fmt)
        risk = BadgeRisk(fmt)
        parsed = risk.parse_raw(sample)
        sev, note = risk.risk_assessment()
        print(f"  [{fmt:9s}] UID={parsed['uid_hex']} risk={sev:6s} — {note}")
    print()

    report = AuditReport(site="ACME HQ", date="2026-09-04")
    report.add_section("Executive Summary",
                       "Perimeter badging present, but loading-dock tailgating risk is HIGH.\n"
                       "EDGE cards are clonable with commodity readers; recommend upgrade to\n"
                       "encrypted credentials (iCLASS SE / DESFire EV2).")
    report.add_section("Findings",
                       "  1. Tailgating: 8/10 attempts unchallenged at loading dock.\n"
                       "  2. Badge cloning: EDGE format is HIGH risk, unauthenticated.\n"
                       "  3. Mantrap absent at main entrance.\n"
                       "  4. No badge person.\n"
                       "  5. Lock-out technicians 1/3 qualified for disc-detainer bypass.")
    report.add_section("Recommendations",
                       "  - Install mantraps or turnstiles at high-value doors.\n"
                       "  - Authorize and train 2 additional lock-out technicians.\n"
                       "  - Migrate from EDGE to encrypted credential platform.\n"
                       "  - Institute tailgating-confrontation drills.")
    print(report.render())
    return 0


if __name__ == "__main__":
    raise SystemExit(demo())